[CmdletBinding(DefaultParameterSetName = 'AllBranches')]
param(
    [Parameter(ParameterSetName = 'AllBranches')]
    [string] $WikiRoot = 'D:\CarlsbergRepos\1760-SmartCore-HUB.wiki',
    [Parameter(ParameterSetName = 'SingleFile', Mandatory = $true)]
    [string[]] $PageFile,
    [switch] $UpdateLive
)

$utf8 = [System.Text.UTF8Encoding]::new($false)
$placeholderRx = [regex]'(?m)^\|(?:\s-\s\|)+\s_[^_]+_\s\|[^\r\n]*\r?\n'

function Invoke-PlaceholderStrip {
    param([string] $Markdown)
    $blocks  = [regex]::Split($Markdown, '(?m)(?=^## )')
    $changed = $false
    for ($i = 0; $i -lt $blocks.Count; $i++) {
        $b = $blocks[$i]
        if ($b -match '(?m)^\|\s*\[' -and $b -match $placeholderRx) {
            $blocks[$i] = $placeholderRx.Replace($b, '', 1)
            $changed = $true
        }
    }
    [pscustomobject]@{ Changed = $changed; Result = if ($changed) { $blocks -join '' } else { $Markdown } }
}

function Write-SamplePair {
    param([string] $SourcePath,[string] $OutDir,[string] $LabelBranch,[bool] $IsSynthetic,[string] $SyntheticFromName,[switch] $UpdateLive)
    $raw  = [System.IO.File]::ReadAllText($SourcePath, $utf8)
    $diag = Invoke-PlaceholderStrip -Markdown $raw
    $base = [System.IO.Path]::GetFileNameWithoutExtension($SourcePath)
    $ext  = [System.IO.Path]::GetExtension($SourcePath)
    $beforePath = Join-Path $OutDir ("{0}-SAMPLE-BEFORE{1}" -f $base, $ext)
    $afterPath  = Join-Path $OutDir ("{0}-SAMPLE-AFTER{1}"  -f $base, $ext)
    $sourceNote = if ($IsSynthetic) { "Synthetic preview - no real $LabelBranch build exists yet on the wiki, so this sample was generated from $SyntheticFromName (latest Release-branch page)." } else { "Real $LabelBranch page snapshot - $base$ext as it currently exists on the wiki." }
    $beforeBanner = "> [!NOTE]`r`n> SAMPLE - BEFORE FIX | Branch: $LabelBranch | Generated by DryRun-NotesPlaceholder.ps1`r`n>`r`n> $sourceNote`r`n>`r`n> Compare with $base-SAMPLE-AFTER$ext. Delete this page once validated.`r`n`r`n---`r`n`r`n"
    $afterChangeNote = if ($diag.Changed) { "Trailing '| - | - | _No release notes..._ | - | - |' placeholder row was stripped from the Notes table because a real data row precedes it. All other content is identical to BEFORE." } else { "No change required. This page already renders correctly with the new fix. Proves the fix is a safe no-op." }
    $afterBanner = "> [!NOTE]`r`n> SAMPLE - AFTER FIX | Branch: $LabelBranch | Generated by DryRun-NotesPlaceholder.ps1`r`n>`r`n> $afterChangeNote`r`n>`r`n> Compare with $base-SAMPLE-BEFORE$ext. Delete this page once validated.`r`n`r`n---`r`n`r`n"
    [System.IO.File]::WriteAllText($beforePath, $beforeBanner + $raw, $utf8)
    [System.IO.File]::WriteAllText($afterPath,  $afterBanner  + $diag.Result, $utf8)
    if ($UpdateLive -and $diag.Changed -and -not $IsSynthetic) {
        [System.IO.File]::WriteAllText($SourcePath, $diag.Result, $utf8)
    }
    [pscustomobject]@{ Branch=$LabelBranch; Synthetic=$IsSynthetic; Source=$SourcePath; Before=$beforePath; After=$afterPath; Changed=$diag.Changed; LiveUpdate=($UpdateLive -and $diag.Changed -and -not $IsSynthetic) }
}

if ($PSCmdlet.ParameterSetName -eq 'SingleFile') {
    $results = foreach ($p in $PageFile) {
        if (-not (Test-Path $p)) { Write-Warning "Skipping missing file: $p"; continue }
        $dir = Split-Path -Parent $p
        Write-SamplePair -SourcePath $p -OutDir $dir -LabelBranch '(adhoc)' -IsSynthetic $false -SyntheticFromName '' -UpdateLive:$UpdateLive
    }
    $results | Format-Table Branch, Changed, LiveUpdate, Before -AutoSize -Wrap
    return
}

$branchMap = [ordered]@{
    'main'    = 'Deployment-release-notes\Main-branch'
    'release' = 'Deployment-release-notes\Release-branch'
    'prod'    = 'Deployment-release-notes\Prod-branch'
    'hotfix'  = 'Deployment-release-notes\Hotfix-branch'
}

function Get-LatestBuildPage {
    param([string] $Dir)
    if (-not (Test-Path $Dir)) { return $null }
    Get-ChildItem $Dir -Filter 'Build-*.md' -ErrorAction SilentlyContinue | Where-Object { $_.Name -notmatch 'SAMPLE|PREVIEW' } | Sort-Object Name -Descending | Select-Object -First 1
}

$results = @()
$releaseLatest = Get-LatestBuildPage -Dir (Join-Path $WikiRoot $branchMap['release'])
foreach ($b in $branchMap.Keys) {
    $dir = Join-Path $WikiRoot $branchMap[$b]
    $latest = Get-LatestBuildPage -Dir $dir
    if ($null -ne $latest) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        $results += Write-SamplePair -SourcePath $latest.FullName -OutDir $dir -LabelBranch $b -IsSynthetic $false -SyntheticFromName '' -UpdateLive:$UpdateLive
    }
    elseif ($null -ne $releaseLatest) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        $synthName = "Build-PREVIEW-from-{0}.md" -f $releaseLatest.BaseName
        $synthPath = Join-Path $dir $synthName
        $rel = [System.IO.File]::ReadAllText($releaseLatest.FullName, $utf8)
        $rel = $rel -replace '(?m)^## Build ', ("## [{0} PREVIEW] Build " -f $b.ToUpper())
        [System.IO.File]::WriteAllText($synthPath, $rel, $utf8)
        $results += Write-SamplePair -SourcePath $synthPath -OutDir $dir -LabelBranch $b -IsSynthetic $true -SyntheticFromName $releaseLatest.Name -UpdateLive:$false
    }
    else {
        Write-Warning "No real $b page and no Release page to synthesise from. Skipping."
    }
}

Write-Host ""
Write-Host "=== Dry-run summary ===" -ForegroundColor Cyan
$results | Format-Table @{N='Branch';E={$_.Branch}}, @{N='Synthetic';E={$_.Synthetic}}, @{N='Stripped';E={$_.Changed}}, @{N='LiveUpd';E={$_.LiveUpdate}}, @{N='SourcePage';E={Split-Path -Leaf $_.Source}} -AutoSize

Write-Host ""
Write-Host "Sample files created (delete once validated):" -ForegroundColor Yellow
$results | ForEach-Object {
    Write-Host ("  [{0}] BEFORE: {1}" -f $_.Branch, $_.Before)
    Write-Host ("  [{0}] AFTER : {1}" -f $_.Branch, $_.After)
}

Write-Host ""
Write-Host "Cleanup commands:" -ForegroundColor DarkGray
Write-Host "  Get-ChildItem '$WikiRoot\Deployment-release-notes' -Recurse -Filter '*SAMPLE-*' | Remove-Item" -ForegroundColor DarkGray
Write-Host "  Get-ChildItem '$WikiRoot\Deployment-release-notes' -Recurse -Filter 'Build-PREVIEW-*' | Remove-Item" -ForegroundColor DarkGray